# Server
server.port=7789
server.host=0.0.0.0

# Application
spring.profiles.active=${APP_ENV:local}

# Logs
logging.level.root=INFO
logging.file.name=logs/jnotifier.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7

# Notification
notification.support.email=mailto://works.sahitya@gmail.com

# File Uploads
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=65MB